// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ProductID    string    `json:"product_id"`
	UserID       string    `json:"user_id"`
	ProductName  string    `json:"product_name"`
	ProductPhoto uuid.UUID `json:"product_photo"`
	Price        int32     `json:"price"`
	Visibility   bool      `json:"visibility"`
}

type User struct {
	UserID          string         `json:"user_id"`
	Username        string         `json:"username"`
	Email           string         `json:"email"`
	Phonenumber     sql.NullString `json:"phonenumber"`
	Password        string         `json:"password"`
	LastLogin       time.Time      `json:"last_login"`
	Isemailverified bool           `json:"isemailverified"`
	Isphoneverified bool           `json:"isphoneverified"`
}

type Useremailverification struct {
	EmailverifyID uuid.UUID `json:"emailverify_id"`
	UserID        string    `json:"user_id"`
	ExpiresAt     time.Time `json:"expires_at"`
	VerifCode     string    `json:"verif_code"`
	Attempts      int16     `json:"attempts"`
	UsedFor       string    `json:"used_for"`
	IsVerified    bool      `json:"is_verified"`
}
